caps:
    consumer_thread: tcb
    consumer_ipc: frame

    producer1_thread: tcb
    producer1_ipc: frame

    producer2_thread: tcb
    producer2_ipc: frame

    shared_endpoint: endpoint


cap_modifications:
    consumer_endpoint:
        original: shared_endpoint
        rights: [read]
    producer1_endpoint:
        original: shared_endpoint
        rights: [write]
        badge: 1234
    producer2_endpoint:
        original: shared_endpoint
        rights: [write]
        badge: 5678

cnodes:
    consumer_cspace:
        size: 5
        guard: 59
        1: consumer_endpoint
    producer1_cspace:
        size: 5
        guard: 59
        1: producer1_endpoint
    producer2_cspace:
        size: 5
        guard: 59
        1: producer2_endpoint

vspaces:
    shared_vspace: thread_elf

threads:
    consumer_thread:
        cspace: consumer_cspace
        vspace: shared_vspace
        ipc_buffer: consumer_ipc
        stack_size: 4096
    producer1_thread:
        cspace: producer1_cspace
        vspace: shared_vspace
        ipc_buffer: producer1_ipc
        stack_size: 4096
        entry: main2
        args: [foo, bar]
    producer2_thread:
        cspace: producer2_cspace
        vspace: shared_vspace
        ipc_buffer: producer2_ipc
        stack_size: 4096
        entry: main2
        args: [foo2, bar2]
