caps:
    thread1_tcb: tcb
    thread1_ipc: frame

    thread2_tcb: tcb
    thread2_ipc: frame

    thread1_frame: frame
    thread2_frame: frame
    thread_endpoint: endpoint


cap_modifications:
    thread1_endpoint:
        original: thread_endpoint
        rights: [write]
        badge: 1234
    thread2_endpoint:
        original: thread_endpoint
        rights: [read]

cnodes:
    thread1_cspace:
        size: 5
        guard: 59
        1: thread1_frame
        2: thread1_endpoint
    thread2_cspace:
        size: 5
        guard: 59
        1: thread2_frame
        2: thread2_endpoint

vspaces:
    thread_vspace: thread_elf

threads:
    thread1_tcb:
        cspace: thread1_cspace
        vspace: thread_vspace
        ipc_buffer: thread1_ipc
        stack_size: 4096
    thread2_tcb:
        cspace: thread2_cspace
        vspace: thread_vspace
        ipc_buffer: thread2_ipc
        stack_size: 4096
        entry: main2